GET http://localhost:9200/_cat/indices?v
Accept: text/plain

###

POST http://localhost:9200/zbmath/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "size": 2,
  "from": 1
}

###

POST localhost:9200/_analyze
Content-Type: application/json

{
  "tokenizer": {"type": "simple_pattern", "pattern": "(m[a-z]+(:[^,)]*|[(])|[)])"},
  "text": "msub(mo:∂,msub(mi:η,mi:x))"
}

###

POST localhost:9200/_analyze
Content-Type: application/json

{
  "tokenizer": "standard",
  "char_filter": [
    "html_strip"
  ],
  "filter": [
    "asciifolding",
    "lowercase"
  ],
  "text": "Let's see if <math id=\"bla\" qid=\"bl2\">f</math> is equal to <math>f(x)</math>"
}

###

POST localhost:9200/arqmath-test-2/_mapping?pretty
Content-Type: application/json


{
  "properties": {
    "email": {
      "type": "keyword"
    }
  }
}


###

DELETE localhost:9200/sinpex-banks
Content-Type: application/json

###
POST localhost:9200/_reindex
Content-Type: application/json

{
  "source": { "index": "arqmath-test" },
  "dest": { "index": "arqmath-test-2" }
}

###

PUT localhost:9200/arqmath-test-2
Content-Type: application/json

{
  "settings": {
    "analysis": {
      "filter": {
        "custom_english_stemmer": {
          "type": "stemmer",
          "name": "english"
        }
      },
      "analyzer": {
        "arqmath_analyzer": {
          "type": "custom",
          "tokenizer": "standard",
          "filter": [
            "asciifolding",
            "lowercase",
            "custom_english_stemmer"
          ]
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "title": {
        "type": "text",
        "index": "false"
      },
      "content": {
        "type": "text",
        "analyzer": "arqmath_analyzer"
      },
      "moi": {
        "type": "nested",
        "properties": {
          "md5": {
            "type": "keyword",
            "index": true
          },
          "tf": {
            "type": "integer",
            "index": true
          }
        }
      }
    }
  }
}

###

PUT localhost:9200/arqmath-test/_doc/2
Content-Type: application/json

{
  "title": "123",
  "content": "Let's dance! With empty MOI blabla",
  "moi": [
    {
      "tf": "2",
      "md5": "mi:r"
    },
    {
      "tf": "4",
      "md5": "mi:Z"
    }
  ]
}

###

GET localhost:9200/arqmath-moi/_doc/9hgHW78E7ueNsGnKAbXdeA==
Content-Type: application/json

###

# Lets put new mapping
PUT localhost:9200/arqmath-test/_mapping
Content-Type: application/json

{
  "properties": {
    "moi": {
      "type": "nested",
      "properties": {
        "md5": {
          "type": "keyword",
          "index": true
        },
        "tf": {
          "type": "integer",
          "index": true
        }
      }
    }
  }
}

###

# And now lets update doc one with mois
POST localhost:9200/arqmath-test/_update/1
Content-Type: application/json

{
  "doc": {
    "moi2": [
      {"md5": "mi:z", "tf": 2},
      {"md5": "mi:a", "tf": 4}
    ]
  }
}
###

POST localhost:9200/arqmath-test/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "content": {
        "query": "dance"
      }
    }
  }
}

###

POST localhost:9200/arqmath-moi/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "size": 2
}

###
GET localhost:9200/arqmath-test/_search
Content-Type: application/json

{
  "query": {
    "nested": {
      "path": "moi",
      "query": {
        "bool": {
          "must": [
            {
              "exists": {
                "field": "moi.md5"
              }
            }
          ]
        }
      }
    }
  },
  "size": 2
}

###
#               "match_all": {}
GET localhost:9200/arqmath/_count
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "nested": {
            "path": "moi",
            "query": {
              "exists": {
                "field": "moi.moiMD5"
              }
            }
          }
        }
      ]
    }
  }
}

###
# Calculate the sum of the document length (or in other words,
# the length of the entire dataset (must be long))
GET localhost:9200/arqmath-data/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "nested": {
            "path": "moi",
            "query": {
              "exists": {
                "field": "moi.moiMD5"
              }
            }
          }
        }
      ]
    }
  },
  "size": 0,
  "aggs": {
    "moi": {
      "nested": {
        "path": "moi"
      },
      "aggs": {
        "totaltf": {
          "sum": {
            "field": "moi.localTermFrequency"
          }
        }
      }
    }
  }
}

###
GET localhost:9200/arqmath-moi/_doc/s38f63Wq5mAfuHrxp3Clog==
Content-Type: application/json

###
GET localhost:9200/arqmath/_search
Content-Type: application/json

{
  "size": 2,
  "query": {
    "match_all": {}
  }
}


###
GET localhost:9200/arqmath/_count
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}