GET http://localhost:9200/_cat/indices?v
Accept: text/plain
###
DELETE localhost:9200/zbmath-moi
###
# curl -X PUT "http://localhost:9200/arxiv-moi" -H 'Content-Type: application/json' -d
# Create zbmath-moi index
PUT localhost:9200/arxiv-moi-test
Content-Type: application/json

{
  "settings": {
    "analysis": {
      "analyzer": {
        "moi_analyzer": {
          "type": "custom",
          "tokenizer": "moi_tokenizer"
        }
      },
      "tokenizer": {
        "moi_tokenizer": {
          "type": "simple_pattern",
          "pattern": "(m[a-z]+(:[^,)]*|[(])|[)])"
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "moi": {
        "type": "text",
        "analyzer": "moi_analyzer"
      },
      "complexity": {
        "type": "short"
      },
      "tf": {
        "type": "integer"
      },
      "df": {
        "type": "integer"
      }
    }
  }
}

###
PUT localhost:9200/arqmath-moi/_mapping
Content-Type: application/json

{
  "properties": {
    "formulaIDs": {
      "type": "keyword"
    }
  }
}

###
# Calculate the sum of the document length (or in other words,
# the length of the entire dataset)
GET localhost:9200/arqmath-data/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "nested": {
            "path": "moi",
            "query": {
              "exists": {
                "field": "moi.moiMD5"
              }
            }
          }
        }
      ]
    }
  },
  "size": 0,
  "aggs": {
    "moi": {
      "nested": {
        "path": "moi"
      },
      "aggs": {
        "totaltf": {
          "sum": {
            "field": "moi.localTermFrequency"
          }
        }
      }
    }
  }
}

###
# Get average complexity of all MOI in arqmath.
# This request doesnt require a "query" because we simply take ALL moi
# so on query at all equals a match_all: {} query.
POST localhost:9200/arqmath-moi/_search
Content-Type: application/json

{
  "size": 0,
  "aggs": {
    "average_complexity": {
      "avg": {
        "field": "complexity"
      }
    }
  }
}

###
POST localhost:9200/zbmath-moi/_search
Content-Type: application/json

{
  "size": 0,
  "aggs": {
    "average_complexity": {
      "avg": {
        "script": {
          "lang": "painless",
          "source": "doc.complexity.value * (doc.tf.value / params.totalTF)",
          "params": {
            "totalTF": 143317218
          }
        }
      }
    }
  }
}

###
POST localhost:9200/arxiv-moi/_search
Content-Type: application/json

{
  "size": 0,
  "aggs": {
    "weighted_average_complexity": {
      "weighted_avg": {
        "value": {
          "field": "complexity"
        },
        "weight": {
          "field": "tf"
        }
      }
    }
  }
}

###
GET localhost:9200/zbmath-moi/_doc/okbFpXNoPCdHP06riJ9Ulg==
Content-Type: application/json

###
# Get the number of documents that contain at least one Math formula
GET localhost:9200/arqmath-moi/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "exists": {
            "field": "formulaIDs"
          }
        }
      ]
    }
  }
}

###
POST localhost:9200/arqmath-moi/_update/okbFpXNoPCdHP06riJ9Ulg==
Content-Type: application/json

{
  "script": {
    "source": "if (ctx._source.formulaIDs == null) {ctx._source.formulaIDs = []} for ( fid in params.newIDs ) {if (!ctx._source.formulaIDs.contains(fid)) {ctx._source.formulaIDs.add(fid)}}",
    "params": {
      "newIDs": ["1"]
    }
  }
}

###
POST localhost:9200/arqmath-moi/_update/okbFpXNoPCdHP06riJ9Ulg==
Content-Type: application/json

{
  "doc": {
    "formulaIDs": []
  }
}
